// SERVER-SIDE ONLY
// Jangan import file ini dari komponen React client.
// File ini berisi password dan hanya boleh digunakan di server/API route.

export const PASSWORD_MAP: Record<string, string> = {
  'Afwina Amni Bayu widi J': 'sukasukakita',
  'Ajeng Wachyu Supramono': 'jeousen',
  'Alika Azzahra': 'kxdur8e45',
  'Alvis Syandana Purwantoro': 'alvisganteng',
  'Alyssa Queenaya warman': 'avangers27',
  'Annisa Luthfi MizQi Hidayak': 'Nisull07',
  'Asadya Akbar Setiawan': 'asaIXsmp11',
  'Athaillah Gibran kurniawan': 'atha1234',
  'Ayu Dhia Syarasana': 'av34ngers27',
  'Azizah Riska Munifah': 'nineaja',
  'Bilal Zaidan winanto': 'bllzaidan13',
  'Calista Adzkia Fatka': '1712060o0',
  'Deda Priyo sembodo': 'AVENGERS',
  'Dhani Fadhil Ibrahim': 'KelasKompak9',
  'Elena Arga kinasih': 'sefarin',
  'Evan Dalvalova Yuwono': 'aasracing53',
  'Faiq Fawwaz Satria': 'So1uZky',
  'Fatimah Az- Zahra': 'imahrt',
  'Hariz Azfarizi': 'Azfarizihariz',
  'Kania Chairinisa Queency': 'kennine',
  'Maia Rania Maharani': 'mairan29._',
  'Mirza Afta Febrian': 'guanyawit',
  'Mohammad Rizki Saputra': 'Rizzzz',
  'Muhammad Hazel Armando': '085743516060',
  "Muhammad Raafi El- Mu'min": 'RFIXSYLH',
  'My Kayla Alexandra P.R': 'kelasKu09',
  'Nadhira Abbiya Saptana': 'Akiramenna',
  'Nareswara Jerry R.P': '9agayabebas',
  'Rafandra Aqlan Lazuardi': 'Kaslana',
  'Riffan Syam Zahir Arthendy': 'padela',
  'Siti Athallah Mumbaz S.H': 'bestclass',
  'Syahla Diaara Brilian': 'syhldrln',
  'Yorji Harlanewa': '88yh11rl81n',
};
